-- phpMyAdmin SQL Dump
-- version 4.8.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 18, 2018 at 06:09 PM
-- Server version: 10.1.31-MariaDB
-- PHP Version: 5.6.35

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `onlinebookstore`
--

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

CREATE TABLE `product` (
  `id` int(10) UNSIGNED NOT NULL,
  `cid` int(11) NOT NULL,
  `imgsrc` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `publisher` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `company` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `detail` text COLLATE utf8_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `hadstock` tinyint(1) NOT NULL DEFAULT '1',
  `price` double(15,2) NOT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`id`, `cid`, `imgsrc`, `title`, `publisher`, `company`, `detail`, `slug`, `hadstock`, `price`, `deleted_at`, `created_at`, `updated_at`) VALUES
(1, 1, '/images/public_download/bengaliimages/ekattor_er_chithi.jpg', ' একাত্তরের চিঠি', 'রণাঙ্গনে মুক্তিযোদ্ধারা ', 'প্রথমা প্রকাশন', ' মুক্তিযুদ্ধের ইতিহাস: ডায়েরি, চিঠি ও স্মৃতিচারণ ', 'ekattor_er_chithi', 10, 10.00, NULL, NULL, NULL),
(2, 1, '/images/public_download/bengaliimages/aguner_poroshmoni.gif', ' আগুনের পরশমণি', 'হাতেখড়ি', 'হুমায়ূন আহমেদ ', 'মুক্তিযুদ্ধভিত্তিক ও রাজনৈতিক উপন্যাস', 'aguner_poroshmoni', 20, 25.00, NULL, NULL, NULL),
(3, 8, '/images/public_download/bengaliimages/deyal.jpg', 'দেয়াল', 'অন্যপ্রকাশ', 'হুমায়ূন আহমেদ', 'ভাদ্র মাসের সন্ধা। আকাশে মেঘ আছে। লালচে রঙের মেঘ। যে মেঘে বৃষ্টি হয় না, তবে দেকায় অপূর্ব। এই গাঢ় লাল, এই হালকা হলুদ, আবার চোখের নিমিষে লালের সঙ্গে খয়েরি মিশে সম্পূর্ণ অন্য রঙ। রঙের খেলা যিনি খেলছেন মনে হয় তিনি সিদ্ধান্তহীনতায় ভুগছেন।', 'deyal', 15, 30.00, NULL, NULL, NULL),
(4, 8, '/images/public_download/bengaliimages/d_tin_dram.gif', ' দ্য টিন ড্রাম', 'অন্যধারা', 'গুন্টার গ্রাস , প্রমিত হোসেন', 'অনুবাদ: উপন্যাস', 'd_tin_dram', 10, 25.00, NULL, NULL, NULL),
(5, 8, '/images/public_download/bengaliimages/puruno_sei_diner_kotha.gif', ' পুরানো সেই দিনের কথা', 'মিত্র ও ঘোষ পাবলিশার্স প্রাঃ লিঃ (ভারত)', 'শ্রী প্রমথনাথ বিশী', 'জীবনী ও স্মৃতিচারণ: বিবিধ', 'puruno_sei_diner_kotha', 10, 50.00, NULL, NULL, NULL),
(6, 8, '/images/public_download/bengaliimages/agun_pakhir_rohossho.jpg', ' আগুন পাখির রহস্য', 'আনন্দ পাবলিশার্স (ভারত)', 'সুনীল গঙ্গোপাধ্যায়', 'পশ্চিমবঙ্গের রহস্য, গোয়েন্দা ও ভৌতিক', 'agun_pakhir_rohossho', 10, 40.00, NULL, NULL, NULL),
(7, 8, '/images/public_download/bengaliimages/osomapto_attojiboni.jpg', ' অসমাপ্ত আত্মজীবনী', 'দি ইউনিভার্সিটি প্রেস লিমিটেড(ইউ পি এল)', 'শেখ মুজিবুর রহমান', 'শেখ মুজিবুর রহমানের লেখা চারটি খাতা ২০০৪ সালে আকস্মিকভাবে তাঁর কন্যা শেখ হাসিনার হস্তগত হয়। খাতাগুলি অতি পুরানো, পাতাগুলি জীর্ণপ্রায় এবং লেখা প্রায়শ অস্পষ্ট। মূল্যবান সেই খাতাগুলি পাঠ করে জানা গেল এটি বঙ্গবন্ধুর অসমাপ্ত আত্মজীবনী, যা তিনি ১৯৬৭ সালের মাঝামাঝি সময়ে ঢাকা সেন্ট্রাল জেলে অন্তরীণ অবস্থায় লেখা শুরু করেছিলেন, কিন্তু শেষ করতে পারেননি। জেল-জুলুম, নিগ্রহ-নিপীড়ন যাঁকে সদা তাড়া করে ফিরেছে, রাজনৈতিক কর্মকাণ্ডে উৎসর্গীকৃত-প্রাণ, সদাব্যস্ত বঙ্গবন্ধু যে আত্মজীবনী লেখায় হাত দিয়েছিলেন এবং কিছুটা লিখেছেনও, এই বইটি তার সাক্ষর বহন করছে। বইটিতে আত্মজীবনী লেখার প্রেক্ষাপট, লেখকের বংশ পরিচয়, জন্ম, শৈশব, স্কুল ও কলেজের শিক্ষাজীবনের পাশাপাশি সামাজিক ও রাজনৈতিক কর্মকাণ্ড, দুর্ভিক্ষ, বিহার ও কলকাতার দাঙ্গা, দেশভাগ, কলকাতাকেন্দ্রিক প্রাদেশিক মুসলিম ছাত্রলীগ ও মুসলিম লীগের রাজনীতি, দেশ বিভাগের পরবর্তী সময় থেকে ১৯৫৪ সাল অবধি পূর্ব বাংলার রাজনীতি, কেন্দ্রীয় ও প্রাদেশিক মুসলিম লীগ সরকারের অপশাসন, ভাষা আন্দোলন, ছাত্রলীগ ও আওয়ামী লীগ প্রতিষ্ঠা, যুক্তফ্রন্ট গঠন ও নির্বাচনে বিজয়ী হয়ে সরকার গঠন, আদমজীর দাঙ্গা, পাকিস্তান কেন্দ্রীয় সরকারের বৈষম্যমূলক শাসন ও প্রাসাদ ষড়যন্ত্রের বিস্তৃত বিবরণ এবং এসব বিষয়ে লেখকের প্রত্যক্ষ অভিজ্ঞতার বর্ণনা রয়েছে। আছে লেখকের কারাজীবন, পিতা-মাতা, সন্তান-সন্ততি ও সর্বোপরি সর্বংসহা সহধর্মিণীর কথা, যিনি তাঁর রাজনৈতিক জীবনে সহায়ক শক্তি হিসেবে সকল দুঃসময়ে অবিচল পাশে ছিলেন। একইসঙ্গে লেখকের চীন, ভারত ও পশ্চিম পাকিস্তান ভ্রমণের বর্ণনাও বইটিকে বিশেষ মাত্রা দিয়েছে।', 'osomapto_attojiboni', 100, 75.00, NULL, NULL, NULL),
(8, 8, '/images/public_download/bengaliimages/kaler_sonkhipto_itihash.GIF', ' কালের সংক্ষিপ্ত ইতিহাস', 'দি স্কাই পাবলিশার্স', 'স্টিফেন হকিং ,  অধ্যাপক সাখাওয়াত হোসেন', 'সূচিপত্র\r\n\r\n* মহাবিশ্ব সম্পর্কে আমাদের চিত্র\r\n* স্থান এবং কাল\r\n* প্রসারমান মহাবিশ্ব\r\n* অনিশ্চয়তাবাদ\r\n* মৌলকণা এবং প্রাকৃতিক বল\r\n* কৃষ্ণগহ্বর\r\n* কৃষ্ণগহ্বর অত কালো নয়\r\n* মহাবিশ্বের উৎপত্তি ও পরিণতি\r\n* সময়ের তীর\r\n* পদার্থবিদ্যাকে ঐক্যবদ্ধ করা\r\n* উপসংহার', 'kaler_sonkhipto_itihash', 10, 20.00, NULL, NULL, NULL),
(9, 1, '/images/public_download/bengaliimages/ekattor_er_diary.jpg', ' একাত্তরের ডায়েরী', 'হাওলাদার প্রকাশনী', 'সুফিয়া কামাল', '১৯১১ সালের ২০ জুন বরিশালের শায়েস্তাবাদের মাতামহের বাড়িতে সুফিয়া কামালের জন্ম। মা সাবেরা বানু এবং বাবা সৈয়দ আব্দুল বারি। পারিবারিক পরিমণ্ডলে সাহিত্য-পত্রিকা ও গল্প পড়তে-পড়তেই সাহিত্যচর্চার অনুপ্রাণিত হন।মাত্র ১৪ বছর বয়সে বরিশাল থেকে ‘তরুণ’ পত্রিকায় ‘সৈনিক বধূ’ গল্পটি তাঁর প্রথম প্রকাশিত রচনা। লেখালেখির কাজ সুফিয়াকে লুকিয়ে করতে হয়েছে-বিশেষ করে বাংলা ভাষার চর্চা ছিলো না। সীমাবদ্ধ ছিল আরবি, ফারসি, উর্দুতে। মায়ের ঐকান্তিক সহযোগিতায় সুফিয়া বাংলা বলতে, পড়তে ও লিখতে শেখেন। লুকিয়ে লুকিয়ে কবিতা রচনা করতে-করতেই সওগাতে প্রকাশিত হল তার প্রথম কবিতা ‘বাসন্তী’ যা সাথে-সাথেই সবার দৃষ্টি আকর্ষণ করে। প্রথম গ্রন্থ রচয়িতা হিসেবে আত্মপ্রকাশ করেন ‘সাঁঝের মায়া’ কাব্যসমগ্র প্রকাশের মাঝে। কবি কাজী নজরুল ইসলাম তাঁকে দীর্ঘ চিঠি লিখে কাব্যচর্চায় উৎসাহিত করেন। প্রকৃতপক্ষে ‘সাঁঝের মায়া’ গ্রন্থের ভূমিকাটি তাঁরই লেখা।বিশ্বকবি রবীন্দ্রনাথ তাঁর কবিতা পড়ে তাঁকে আর্শীবাণী পাঠিয়েছিলেন এই বলে, ‘তোমার কবিত্ব আমাকে বিস্মিত করে। বাংলা সাহিত্যে তোমার স্থান উচ্চে এবং ধ্রুত তোমার প্রতিষ্ঠা আমার আশির্বাদ গ্রহণ করো।’ (সেলিম জাহাঙ্গীর, সুফিয়া কামাল, নারী উদ্যোগ কেন্দ্র, ঢাকা ১৯৯৩ পৃ-৬৪) সওগাত সম্পাদক মোহাম্মদ নাসিরুদ্দীন তাঁর সাহিত্য-জীবনে উৎসাহের বিরাট উৎস হিসেবে কাজ করেছেন।', 'ekattor_er_diary', 10, 60.00, NULL, NULL, NULL),
(10, 8, '/images/public_download/bengaliimages/sharlok_homes_somogro.jpg', ' শার্লক হোমস সমগ্র', 'শিকড়', 'স্যার আর্থার কোনান ডয়েল', 'রহস্য ও গোয়েন্দা', 'sharlok_homes_somogro', 10, 45.00, NULL, NULL, NULL),
(11, 5, '/images/public_download/bengaliimages/origin.jpg', 'অরিজিন', 'অন্যধারা', 'ড্যান ব্রাউন , রাব্বি উস সানী , অমিত রহমান', 'অনুবাদ রহস্য, ভৌতিক, থ্রিলার ও অ্যাডভেঞ্চার', 'origin', 10, 25.00, NULL, NULL, NULL),
(12, 7, '/images/public_download/bengaliimages/prodigi.jpg', ' বৈজ্ঞানিক কল্পকাহিনী : প্রডিজি', 'জ্ঞানকোষ প্রকাশনী', 'মুহম্মদ জাফর ইকবাল', 'সায়েন্স ফিকশন', 'prodigi', 10, 30.00, NULL, NULL, NULL),
(19, 2, '/images/public_download/computerartimages/Stanley.Computer10.jpg', 'Windows 10 The Missing Manual', 'O\'Reilly Media', 'David Pogue ', 'With Windows 8, Microsoft completely reimagined the graphical user interface for its operating system, which now runs on both desktop PCs and tablets, but the overhaul was not without hitches and its dueling UIs (one designed for touch, the other for keyboards and mice) created significant confusion for users. Windows 10 (a free update to users of Windows 8 or Windows 7) fixes a number of the problems introduced by the revolution in Windows 8 and offers plenty of new features along, such as the new Spartan web browser, Cortana voice-activated ¡§personal assistant,¡¨ new universal apps (that run on tablet, phone, and computer), and more. But to really get the most out of the new operating system, you¡¦re going to need a guide.', 'windows-10-the-missing-manual', 1, 23.00, NULL, '2018-03-07 23:17:33', '2018-04-15 20:58:22'),
(27, 3, '/images/public_download/historyimages/Johnny.History8.jpg', 'The Geography Of Genius: A Search For The World\'s Most Creative Places From Ancient Athens To Silicon Valley', 'Eric Weiner', 'Simon & Schuster', 'Travel the world with Eric Weiner, the New York Times bestselling author of The Geography of Bliss, as he journeys from Athens to Silicon Valley—and throughout history, too—to show how creative genius flourishes in specific places at specific times.', 'the-geography-of-genius-a-search-for-the-world-s-most-creative-places-from-ancient-athens-to-silicon-valley', 1, 101.00, NULL, '2018-03-13 03:51:01', '2018-04-15 20:58:40'),
(28, 3, '/images/public_download/historyimages/Johnny.History9.jpg', 'Fighter Pilot', 'Paul Richey', 'The History Press', 'The first and finest story of a fighter pilot in World War Two. Thus Group Captain Peter Townsend described Paul Richey\\’s classic account of his part in the desperate battles over France in May of 1940. ', 'fighter-pilot', 1, 118.00, NULL, '2018-02-28 08:59:49', '2018-04-15 20:58:41'),
(29, 3, '/images/public_download/historyimages/Johnny.History10.jpg', 'Commander Will Cushing: Daredevil Hero Of The Civil War', 'Jamie Malanowski', 'W. W. Norton & Company', 'Superbly entertaining.―S. C. Gwynne, best-selling author of Empire of the Summer Moon', 'commander-will-cushing-daredevil-hero-of-the-civil-war', 1, 118.00, NULL, '2018-03-10 02:35:24', '2018-04-15 20:58:41'),
(30, 3, '/images/public_download/historyimages/Johnny.History11.jpg', 'Paris Reborn: Napoléon III, Baron Haussmann, And The Quest To Build A Modern City', 'Stephane Kirkland', 'St. Martin\'s Griffin', 'Stephane Kirkland gives an engrossing account of Napoleon III, Baron Haussmann, and one of the greatest transformations of a major city in modern history', 'paris-reborn-napoleon-iii-baron-haussmann-and-the-quest-to-build-a-modern-city', 1, 78.00, NULL, '2018-03-06 06:28:13', '2018-04-15 20:58:43'),
(32, 3, '/images/public_download/historyimages/Johnny.History13.jpg', 'Now I Know More: The Revealing Stories Behind Even More Of The World\'s Most Interesting Facts', 'Dan Lewis', 'Adams Media', 'Every story in the book is interesting, and Lewis includes a bonus fact at the end of each story, which is a mini mind bender on its own.', 'now-i-know-more-the-revealing-stories-behind-even-more-of-the-world-s-most-interesting-facts', 1, 93.00, NULL, '2018-02-22 01:32:13', '2018-04-15 20:58:51'),
(34, 3, '/images/public_download/historyimages/Johnny.History15.jpg', 'Lafayette In The Somewhat United States ', 'Sarah Vowell', 'Riverhead Books', 'From the bestselling author of Assassination Vacation and The Partly Cloudy Patriot, an insightful and unconventional account of George Washington\\’s trusted officer and friend, that swashbuckling teenage French aristocrat the Marquis de Lafayette.', 'lafayette-in-the-somewhat-united-states', 1, 110.00, NULL, '2018-02-19 18:35:52', '2018-04-15 20:58:54'),
(36, 3, '/images/public_download/historyimages/Johnny.History17.jpg', 'Charlie Mike: A True Story Of Heroes Who Brought Their Mission Home', 'Joe Klein', 'Simon & Schuster', 'This is the true story of two decorated combat veterans linked by tragedy, who come home from the Middle East and find a new way to save their comrades and heal their country.', 'charlie-mike-a-true-story-of-heroes-who-brought-their-mission-home', 1, 101.00, NULL, '2018-03-05 12:12:45', '2018-04-15 20:59:14'),
(37, 3, '/images/public_download/historyimages/Johnny.History18.jpg', 'The Witch Of Lime Street: Séance, Seduction, And Houdini In The Spirit World', 'David Jaher', 'Crown', 'History comes alive in this textured account of the rivalry between Harry Houdini and the so-called Witch of Lime Street, whose iconic lives intersected at a time when science was on the verge of embracing the paranormal.', 'the-witch-of-lime-street-seance-seduction-and-houdini-in-the-spirit-world', 1, 110.00, NULL, '2018-02-26 05:10:19', '2018-04-15 20:59:18'),
(39, 3, '/images/public_download/historyimages/Johnny.History20.jpg', 'Tambora: The Eruption That Changed The World', 'Gillen D. Arcy Wood', 'Princeton University Press', 'When Indonesia\'s Mount Tambora erupted in 1815, it unleashed the most destructive wave of extreme weather the world has witnessed in thousands of years. ', 'tambora-the-eruption-that-changed-the-world', 1, 117.00, NULL, '2018-02-26 09:34:57', '2018-04-15 20:59:47'),
(42, 4, '/images/public_download/travelchildrenimages/Helen.Children3.jpg', 'Ten Tiny Toes', 'Caroline Jayne Church ', 'Cartwheel Books', 'Caroline Jayne Church brings her adorable toddler art and lovely rhymes to this joyful twist on the tried-and-true classic, HEAD, SHOULDERS, KNEES, AND TOES. From ears that wiggle to bellies that giggle, TEN TINY TOES is sure to inspire little ones as they learn to celebrate their mouth, ears, eyes, nose, and a love that grows and grows.', 'ten-tiny-toes', 1, 102.00, NULL, '2018-03-07 02:58:46', '2018-04-15 21:00:08'),
(44, 4, '/images/public_download/travelchildrenimages/Helen.Children5.jpg', 'Little Blue Truck Leads The Way Board Book', 'Alice Schertle, Jill McElmurry', 'HMH Books For Young Readers', 'Zooom! Wooeeee . . . ! \"Make way!\" The big city sure is a speedy, noisy place for a country truck like Blue. Everywhere Blue looks, he sees buses, police cars, taxis, vans, a street sweeper, and even the mayor’s limousine. With everyone pushing to be first, soon there’s a giant traffic jam! But even a wrangle-tangle is no match for Little Blue Truck, who comes to the rescue in true Blue style. Brimming with bright colors, sounds, and city energy, this adventure makes working together and taking turns more fun than ever. Now with a free downloadable party kit!', 'little-blue-truck-leads-the-way-board-book', 1, 88.00, NULL, '2018-02-21 01:33:41', '2018-04-15 21:00:20'),
(46, 4, '/images/public_download/travelchildrenimages/Helen.Children7.jpg', 'The Story Of Diva And Flea', 'Mo Willems, Tony DiTerlizzi', 'Disney-Hyperion', 'For as long as she could remember, Diva lived at 11 avenue Le Play in Paris, France. For as long as he could remember, Flea also lived in Paris, France-but at no fixed address. When Flea fl neurs past Diva\'s courtyard one day, their lives are forever changed. Together, Diva and Flea explore and share their very different worlds, as only true friends can do.', 'the-story-of-diva-and-flea', 1, 70.00, NULL, '2018-03-01 23:45:05', '2018-04-15 21:00:27'),
(47, 4, '/images/public_download/travelchildrenimages/Helen.Children8.jpg', 'Mr. Putter & Tabby Turn The Page', 'Cynthia Rylant, Arthur Howard', 'HMH Books For Young Readers', 'Mr. Putter and his fine cat, Tabby, love reading their favorite books over and over. So when Mr. Putter sees a sign at the library that says “Read Aloud with Your Pet at Story Time,” he signs up! But then Mr. Putter\'s friend and neighbor, Mrs. Teaberry, wants to join. If Mrs. Teaberry brings her good dog, Zeke, to the library, who knows what will happen? With Zeke up to his usual tricks, story time might get too exciting! This volume in the beloved Mr. Putter and Tabby series was named a Geisel Honor Book by the American Library Association.', 'mr-putter-tabby-turn-the-page', 1, 92.00, NULL, '2018-02-23 05:07:47', '2018-04-15 21:00:28'),
(48, 4, '/images/public_download/travelchildrenimages/Helen.Children9.jpg', 'Diary Of A Wimpy Kid: Old School', 'Jeff Kinney', 'Amulet Books', 'Life was better in the old days. Or was it? That’s the question Greg Heffley is asking as his town voluntarily unplugs and goes electronics-free. But modern life has its conveniences, and Greg isn’t cut out for an old-fashioned world. With tension building inside and outside the Heffley home, will Greg find a way to survive? Or is going “old school” just too hard for a kid like Greg?', 'diary-of-a-wimpy-kid-old-school', 1, 103.00, NULL, '2018-02-25 09:47:37', '2018-04-15 21:00:30'),
(49, 4, '/images/public_download/travelchildrenimages/Helen.Children10.jpg', 'Guinness World Records 2016', 'Guinness World Records', 'Guinness World Records', 'As well as all your favorite records for talented pets, superhuman achievements, big stuff and extreme vehicles, you\'ll find show-stopping superlatives from brand-new categories. Topics making their GWR debut include waterfalls, twins, ballooning, apps, lightning, manga, archaeology, drones, and pirates - and that\'s just for starters!', 'guinness-world-records-2016', 1, 150.00, NULL, '2018-02-27 14:25:57', '2018-04-15 21:00:36'),
(51, 5, '/images/public_download/travelchildrenimages/Helen.Travel2.jpg', 'Journeys Of A Lifetime: 500 Of The World\'s Greatest Trips', 'National Geographic', 'National Geographic', 'Journeys of a Lifetime spans the globe to highlight the best of the world\'s most famous and lesser known sojourns. It presents an incredible diversity of possibilities, from ocean cruises around Antarctica to horse treks in the Andes. Every continent and every possible form of transport is covered. ', 'journeys-of-a-lifetime-500-of-the-world-s-greatest-trips', 1, 299.00, NULL, '2018-03-03 18:48:59', '2018-04-15 21:00:37'),
(54, 5, '/images/public_download/travelchildrenimages/Helen.Travel5.jpg', 'The Catskills: Its History And How It Changed America', 'Stephen M. Silverman, Raphael D. Silver', 'Knopf', 'Stephen Silverman and Raphael Silver tell of the turning points that made the Catskills so vital to the development of America', 'the-catskills-its-history-and-how-it-changed-america', 1, 144.00, NULL, '2018-02-26 20:35:04', '2018-04-15 21:00:54'),
(55, 5, '/images/public_download/travelchildrenimages/Helen.Travel6.jpg', 'Top 10 Iceland', 'DK Publishing', 'DK Eyewitness Travel', 'Rely on dozens of Top 10 lists — from the Top 10 nightlife hotspots to the Top 10 volcanoes, waterfalls, and hiking trails. And to save you time and money, there is even a list of budget tips and the Top 10 things to avoid.', 'top-10-iceland', 1, 144.00, NULL, '2018-03-05 09:56:03', '2018-04-15 21:00:57'),
(56, 5, '/images/public_download/travelchildrenimages/Helen.Travel7.jpg', 'Level Up Your Life: How To Unlock Adventure And Happiness By Becoming The Hero Of Your Own Story', 'Steve Kamb', 'Rodale Books', 'Level Up Your Life uses the principles of video games, movies, television, comic books, and pop culture to teach you how to transform your life in extraordinary ways and collect real-world experiences that are just as amazing and fulfilling as the adventures of comic book heroes and video game characters. Learn how to design your own personal Epic Quest of Awesome through advice on health, fitness, travel, and finance.', 'level-up-your-life-how-to-unlock-adventure-and-happiness-by-becoming-the-hero-of-your-own-story', 1, 175.00, NULL, '2018-02-17 01:33:31', '2018-04-15 21:01:05'),
(57, 5, '/images/public_download/travelchildrenimages/Helen.Travel8.jpg', 'Southern Living 50 Years: A Celebration Of People, Places, And Culture', 'The Editors Of Southern Living Magazine', 'Oxmoor House', 'For the last 50 years, Southern Living magazine has reported on and photographed what makes the South so very unique and how it has evolved; it\'s distinct regions, its music, its homes, its gardens, its food, and most importantly, its people. Now, to mark its Golden Anniversary, Southern Living presents a gorgeous gift book that tells the true story of the South as only Southerners and Southern Living can tell it. ', 'southern-living-50-years-a-celebration-of-people-places-and-culture', 1, 177.00, NULL, '2018-03-02 19:40:09', '2018-04-15 21:01:08'),
(58, 5, '/images/public_download/travelchildrenimages/Helen.Travel9.jpg', 'Barbarian Days: A Surfing Life', 'William Finnegan', 'Penguin Press', 'Barbarian Days is an old-school adventure story, an intellectual autobiography, a social history, a literary road movie, and an extraordinary exploration of the gradual mastering of an exacting, little understood art. Today, Finnegan’s surfing life is undiminished. Frantically juggling work and family, he chases his enchantment through Long Island ice storms and obscure corners of Madagascar.', 'barbarian-days-a-surfing-life', 1, 181.00, NULL, '2018-03-12 09:42:28', '2018-04-15 21:01:11'),
(59, 5, '/images/public_download/travelchildrenimages/Helen.Travel10.jpg', 'All The Buildings In New York: That I\'ve Drawn So Far', 'Universe', 'James Gulliver Hancock', 'A charmingly illustrated journey through New York City, neighborhood by neighborhood. All the Buildings in New York is a love letter to New York City, told through James Gulliver Hancock’s unique and charming drawings of the city’s diverse architectural styles and cityscape.', 'all-the-buildings-in-new-york-that-i-ve-drawn-so-far', 1, 600.00, NULL, '2018-02-18 08:02:24', '2018-04-15 21:01:16'),
(70, 6, '/images/public_download/computerartimages/Stanley.Art1.jpg', 'Andy Goldsworthy: Ephemeral Works', 'Andy Goldsworthy', 'Harry N. Abrams', 'On an almost daily basis, Andy Goldsworthy makes art using the materials and conditions he encounters wherever he is, be it the land around his Scottish home, the mountain regions of France or Spain, or the sidewalks of New York City, Glasgow, or Rio de Janeiro. Out of earth, rocks, leaves, ice, snow, rain, sunlight, and shadow he creates works that exist briefly before they are altered and erased by natural processes. They are documented in his photographs, and their larger meanings are bound up with the forces that they embody: materiality, temporality, growth, vitality, permanence, decay, chance, labor, and memory.', 'andy-goldsworthy-ephemeral-works', 1, 54.00, NULL, '2018-02-22 23:58:44', '2018-04-15 20:57:33'),
(72, 6, '/images/public_download/computerartimages/Stanley.Art2.jpg', 'Covert To Overt The UnderOverground Art Of Shepard Fairey', 'Shepard Fairey', 'Rizzoli', 'His signature blend of politics, street culture, and art makes Fairey unlike any other subculture/street artist working today. \n		This book showcases the significant amount of art he has created the last several years: street murals, mixed-media installations, art/music events, countless silk screens, and work from his extremely successful OBEY brand.', 'covert-to-overt-the-underoverground-art-of-shepard-fairey', 1, 32.00, NULL, '2018-02-19 03:46:29', '2018-04-15 20:57:34'),
(73, 6, '/images/public_download/computerartimages/Stanley.Art3.jpg', 'Dust & Grooves Adventures In Record Collecting', 'Eilon Paz', 'Ten Speed Press', 'Dust & Grooves: Adventures in Record Collecting is an inside look into the world of vinyl record collectors in the most intimate of environments¡Xtheir record rooms. Compelling photographic essays from photographer Eilon Paz are paired with in-depth and insightful interviews to illustrate what motivates these collectors to keep digging for more records. The reader gets an up close and personal look at a variety of well-known vinyl champions, including Gilles Peterson and King Britt, as well as a glimpse into the collections of known and unknown DJs, producers, record dealers, and everyday enthusiasts. Driven by his love for vinyl records, Paz takes us on a five-year journey unearthing the very soul of the vinyl community.', 'dust-grooves-adventures-in-record-collecting', 1, 32.00, NULL, '2018-03-15 12:04:22', '2018-04-15 20:57:34'),
(84, 6, '/images/public_download/computerartimages/Stanley.Art4.jpg', 'Every Person In New York', 'Jason Polan', 'Chronicle Books', 'Jason Polan is on a mission to draw every person in New York, from cab drivers to celebrities. He draws people eating at Taco Bell, admiring paintings at the Museum of Modern Art, and sleeping on the subway. With a foreword by Kristen Wiig, Every Person in New York, Volume 1 collects thousands of Polan\'s energetic drawings in one chunky book. As full as a phone book and as invigorating as a walk down a bustling New York street, this is a new kind of love letter to a beloved city and the people who live there.', 'every-person-in-new-york', 1, 16.00, NULL, '2018-03-10 14:04:53', '2018-04-15 20:57:36'),
(85, 6, '/images/public_download/computerartimages/Stanley.Art6.jpg', 'Maya Lin Topologies', 'Maya Lin', 'Rizzoli', 'The first comprehensive monograph on the acclaimed American artist and architect, known for her environmental works and memorials that distill a tranquil yet texturally rich minimalism. ?Maya Lin is one of the most important public artists of this century. As an architecture student at Yale, Lin designed the Vietnam Veterans Memorial as a class project, entering it in the largest design competition in American history. Her winning proposal, a V-shaped wall of black stone etched with the names of 58,000 dead soldiers, has since become the most visited memorial in the nation¡¦s capital.This visually rich volume presents 50 projects from the last three decades that demonstrate the scope of Lin¡¦s creative process, featuring her own sketches and drawings and linked by her ideal of making a place for individuals within the landscape. With her environmental works Storm King Wavefield, Eleven-Minute Line (Sweden), and Pin River¡VYangtze (Beijing), Lin maintains a balance between art and architecture, drawing inspiration from culturally diverse sources.', 'maya-lin-topologies', 1, 41.00, NULL, '2018-02-27 17:57:45', '2018-04-15 20:57:44'),
(86, 6, '/images/public_download/computerartimages/Stanley.Art6.jpg', 'Maya Lin Topologies', 'Maya Lin', 'Rizzoli', 'The first comprehensive monograph on the acclaimed American artist and architect, known for her environmental works and memorials that distill a tranquil yet texturally rich minimalism. ?Maya Lin is one of the most important public artists of this century. As an architecture student at Yale, Lin designed the Vietnam Veterans Memorial as a class project, entering it in the largest design competition in American history. Her winning proposal, a V-shaped wall of black stone etched with the names of 58,000 dead soldiers, has since become the most visited memorial in the nation¡¦s capital.This visually rich volume presents 50 projects from the last three decades that demonstrate the scope of Lin¡¦s creative process, featuring her own sketches and drawings and linked by her ideal of making a place for individuals within the landscape. With her environmental works Storm King Wavefield, Eleven-Minute Line (Sweden), and Pin River¡VYangtze (Beijing), Lin maintains a balance between art and architecture, drawing inspiration from culturally diverse sources.', 'maya-lin-topologies-1', 1, 41.00, NULL, '2018-03-05 17:32:23', '2018-04-15 20:57:49'),
(87, 6, '/images/public_download/computerartimages/Stanley.Art8.jpg', 'The Butterflies Of North America Titian Peale\'s Lost Manuscript', 'Kenneth Haltman', 'Harry N. Abrams', 'The American artist and naturalist Titian Ramsay Peale II (1799¡V1885) had a passion for butterflies, and throughout his long life he wrote and illustrated an ambitious and comprehensive manuscript. The book, along with a companion volume on caterpillars, was never published, and it resides today in the Rare Book Collection of the American Museum of Natural History in New York. Now Peale¡¦s color plates, lovingly prepared for the printer by the artist more than 100 years ago, will be published for the first time in this beautiful volume. At last, Peale¡¦s life work, equivalent in scope and beauty to Audubon¡¦s Birds of North America, will be available to a wide audience. The book includes a foreword by Ellen V. Futter and text by Kenneth Haltman and David A. Grimaldi that describes the art and science Peale brought to his extraordinary work.', 'the-butterflies-of-north-america-titian-peale-s-lost-manuscript', 1, 24.00, NULL, '2018-02-28 00:55:40', '2018-04-15 20:57:55'),
(88, 6, '/images/public_download/computerartimages/Stanley.Art10.jpg', 'The Hirschfeld Century: Portrait Of An Artist And His Age', 'Mark E. Hogancamp', 'Chris Shellen', 'In April 2000, Mark Hogancamp was beaten and left for dead outside a bar in his hometown of Kingston, NY. Waking from a nine-day coma, he had no memory of the thirty-eight prior years of his life, including his ex-wife, family, artistic talents, or military service. To reconstruct his past, Hogancamp built, in his backyard, Marwencol, an imaginary village set in World War II Belgium, where everybody is welcome¡XGermans, Americans, French, British, and Russians¡Xas long as peace is kept. With 1:6 scale action figures and Barbie dolls, as well as toy armaments and meticulously built props, buildings, and clothes, Marwencol is an alternate reality, created with painstaking (and sometimes painful) realism and obsessive attention to detail.', 'the-hirschfeld-century-portrait-of-an-artist-and-his-age-1', 1, 35.00, NULL, '2018-03-08 23:38:05', '2018-04-15 20:58:00'),
(89, 2, '/images/public_download/computerartimages/Stanley.Computer1.jpg', 'About Face The Essentials Of Interaction Design 4th Edition', 'Alan Cooper', 'Wiley', 'The essential interaction design guide, fully revised and updated for the mobile age About Face: The Essentials of Interaction Design, Fourth Edition is the latest update to the book that shaped and evolved the landscape of interaction design. This comprehensive guide takes the worldwide shift to smartphones and tablets into account. New information includes discussions on mobile apps, touch interfaces, screen size considerations, and more. The new full-color interior and unique layout better illustrate modern design concepts. The interaction design profession is blooming with the success of design-intensive companies, priming customers to expect \"design\" as a critical ingredient of marketplace success.', 'about-face-the-essentials-of-interaction-design-4th-edition', 1, 20.00, NULL, '2018-03-06 15:16:00', '2018-04-15 20:58:00'),
(90, 2, '/images/public_download/computerartimages/Stanley.Computer2.jpg', 'Android Native Development Kit Cookbook', 'Feipeng Liu', 'Packt Publishing', 'Feipeng Liu is a technology enthusiast with a focus on multimedia systems and applications. He started mobile applications development in 2008 on Windows Mobile. In 2010, he started developing apps for Android with NDK. His Android apps have been used by many users. One of his apps, Video Converter Android, reached 1 million downloads within 10 months. Feipeng received his B.ENG in Electrical and Electronic Engineering, Nanyang Technological University and Master of Computing degree in the Department of Computer Science, National University of Singapore.', 'android-native-development-kit-cookbook', 1, 76.00, NULL, '2018-03-12 13:02:30', '0000-00-00 00:00:00'),
(91, 2, '/images/public_download/computerartimages/Stanley.Computer3.jpg', 'Android NDK Beginners Guide - Second Edition', 'Sylvain Ratabouil', 'Packt Publishing', 'Sylvain Ratabouil is an IT consultant, experienced in Android, Java, and C/C++. He has contributed to the development of digital and mobile applications for large companies as well as industrial projects for the space and aeronautics industries. As a technology lover, he is passionate about mobile technologies and cannot live without his Android smartphone.', 'android-ndk-beginners-guide-second-edition', 1, 49.00, NULL, '2018-02-24 06:53:19', '2018-04-15 20:58:05'),
(92, 2, '/images/public_download/computerartimages/Stanley.Computer4.jpg', 'Badass Making Users Awesome', 'Kathy Sierra', 'O\'Reilly Media', 'The design and layout of this book play a key role in conveying the author\'s message. When creating the ebooks, we\'ve tried to keep the look and feel of the print edition, but this means that not all e-reading devices will support the files. The EPUB format is optimized for iPad. The Mobi files are optimized for Kindle Fire tablets and phones and for Kindle reading apps.', 'badass-making-users-awesome', 1, 21.00, NULL, '2018-02-24 11:28:19', '2018-04-15 20:58:09'),
(93, 2, '/images/public_download/computerartimages/Stanley.Computer5.jpg', 'Internet Congestion Control 1st Edition', 'Subir Varma', 'Morgan Kaufmann', 'The field of congestion control has seen many notable advances in recent years and the purpose of this book, which is targeted towards the advanced and intermediate reader, is to inform about the most important developments in this area. The book should enable the reader to gain a good understanding of the application of congestion control theory to a number of application domains such as Data Center Networks, Video Streaming, High Speed Links and Broadband Wireless Networks. When seen through the lens of analytical modeling, there are a number of common threads that run through the design and analysis of congestion control protocols in all these different areas, which are emphasized in this book. The book also cuts a path through the profusion of algorithms in the literature, and puts the topic on a systematic and logical footing.', 'internet-congestion-control-1st-edition', 1, 57.00, NULL, '2018-03-06 22:04:02', '2018-04-15 20:58:10'),
(94, 2, '/images/public_download/computerartimages/Stanley.Computer6.jpg', 'Internet Measurement Infrastructure, Traffic And Applications', 'Balachander Krishnamurthy Mark Crovella', 'Wiley, John & Sons, Incorporated', 'Although the Internet is now a planet-wide communication medium, we have remarkably little quantitative understanding of it. This ground breaking book provides a comprehensive overview of the important field of Internet Measurement, and includes a first detailed look at three areas: measurements of Internet infrastructure: routers, links, network connectivity and bandwidth, measurements of traffic on the Internet: packets, bytes, flows, sessions, etc., measurements of various key Internet applications: DNS, Web, Peer-to-Peer, and networked games.', 'internet-measurement-infrastructure-traffic-and-applications', 1, 586.00, NULL, '2018-02-18 15:44:10', '2018-04-15 20:58:14'),
(95, 2, '/images/public_download/computerartimages/Stanley.Computer7.jpg', 'Pro Android C++ With The NDK', 'Onur Cinar', 'Apress', 'Onur Cinar has over 17 years of experience in design, development, and management of large scale complex software projects, primarily in mobile and telecommunication space. His expertise spans VoIP, video communication, mobile applications, grid computing, and networking technologies on diverse platforms. He has been actively working with Android platform since its beginning. He has a Bachelor of Science degree in Computer Science from Drexel University in Philadelphia, PA, United States. He is currently working at Skype as the Sr. Product Engineering Manager for Skype client on Android platform.', 'pro-android-c-with-the-ndk', 1, 32.00, NULL, '2018-03-14 01:28:30', '2018-04-15 20:58:15'),
(96, 2, '/images/public_download/computerartimages/Stanley.Computer8.jpg', 'Unity In Action Multiplatform Game Development In C# With Unity 5', 'Joe Hocking', 'Manning Publications', 'This book helps readers build successful games with the Unity game development platform. You will use the powerful C# language, Unity\'s intuitive workflow tools, and a state-of-the-art rendering engine to build and deploy mobile, desktop, and console games. Unity\'s single codebase approach minimizes inefficient switching among development tools and concentrates your attention on making great interactive experiences.', '', 1, 23.00, NULL, '2018-03-13 16:28:26', '2018-04-15 20:58:16');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `product`
--
ALTER TABLE `product`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=97;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
